inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7.2
  TargetRailsVersion: 6.1.4.4

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Rails/Presence:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 7

CUL/CapybaraScreenshots:
  Description: 'Disallow calls to save_screenshot in feature specs.'
  Enabled: true
  VersionAdded: '3.2.2'
  Include:
    - 'spec/**/*'
