inherit_gem:
  rubocul: rubocul_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.0
  TargetRailsVersion: 7.0.1

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Rails/Presence:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 7

CUL/CapybaraScreenshots:
  Description: 'Disallow calls to save_screenshot in feature specs.'
  Enabled: true
  VersionAdded: '3.2.2'
  Include:
    - 'spec/**/*'

Rails/DynamicFindBy:
  Whitelist:
    - find_by_uid!
    - find_by_uid
    - find_by_path_traversal
    - find_by_sparql_relationship
    - find_by_string_key

RSpec/PredicateMatcher:
  Enabled: false

# Temporarily disabling the following cops (which may be useful, but currently cause too many warnings):
# Note: Some of these occurrences should be changed in batch later (potentially using rubocop auto-correct).

Style/StringLiterals:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/ContextMethod:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
