require: rubocop-rspec

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4.2
  TargetRailsVersion: 4.10
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'app/helpers/**/*'
    - 'app/views/**/*'
    - 'lib/tasks/**/*'
    - 'app/controllers/concerns/hyacinth/digital_objects/downloads.rb'
    - 'app/controllers/assignments_controller.rb'
    - 'app/controllers/assignments/changesets_controller.rb'
    - 'app/models/digital_object/asset.rb'
    - 'app/models/concerns/digital_object/assets/validations.rb'
    - 'local/**/*'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Lint/UriEscapeUnescape:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/hyacinth/xml_generator/element.rb'
    - 'app/jobs/process_digital_object_import_job.rb'
    - 'app/models/concerns/digital_object/persistence.rb'
    - 'app/models/concerns/digital_object/publishing.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/hyacinth/xml_generator/element.rb'
    - 'app/jobs/process_digital_object_import_job.rb'
    - 'app/models/concerns/digital_object/persistence.rb'
    - 'app/models/concerns/digital_object/publishing.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/digital_objects_controller.rb'
  CountComments: false  # count full line comments?
  Max: 300

Metrics/ModuleLength:
  Exclude:
    - 'app/models/concerns/digital_object/fedora.rb'
    - 'app/models/concerns/digital_object/assets/file_import.rb'
  CountComments: false
  Max: 110

Naming/PredicateName:
  Exclude: []

Performance/RegexpMatch:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude: []

Style/LineEndConcatenation:
  Exclude: []

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude: []

Style/SignalException:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'
    - 'lib/hyacinth/utils/logger.rb'
    - 'config/deploy.rb'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/jobs/event_jobs_spec.rb'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
