# frozen_string_literal: true
require 'json'
class Hyacinth::Adapters::ExternalIdentifierAdapter::Datacite::RestApi::V2::Api
  # Events used when minting a DOI, depends on desired state of minted DOI
  # see https://support.datacite.org/docs/how-do-i-make-a-findable-doi-with-the-rest-api
  DOI_MINT_EVENT = { draft: '',
                     findable: 'publish',
                     registered: 'hide' }.freeze

  # @param datacite_rest_api_url [String] url for the DataCite REST API
  # @param basic_auth_user [String] username used to authenticate on the API
  # @param basic_auth_password [String] password used to authenticate on the API
  def initialize(datacite_rest_api_url = DATACITE[:rest_api],
                 basic_auth_user = DATACITE[:user],
                 basic_auth_password = DATACITE[:password])
    @datacite_rest_api_url = datacite_rest_api_url
    @basic_auth_user = basic_auth_user
    @basic_auth_password = basic_auth_password
  end

  # see https://support.datacite.org/reference/dois-2#get_dois-id
  # @param doi [String] DOI
  # @return [Faraday::Response] response from the DataCite REST API
  def get_dois(doi)
    conn = Faraday.new(@datacite_rest_api_url)
    conn.basic_auth(@basic_auth_user, @basic_auth_password)
    response = conn.get("/dois/#{doi}")
    log("API response body: #{response.body}", DATACITE[:log_level]) if DATACITE[:log_api]
    response
  end

  def log(log_msg, log_level)
    return if ['debug', 'info', 'warn', 'error', 'fatal', 'unknown'].exclude? log_level
    Rails.logger.public_send(log_level, log_msg)
  end

  # @param api_http_response_body [String] the body content from the response generated by the DataCite REST API
  # @return [String] the doi contained within the DataCite REST API response
  def parse_doi_from_api_response_body(api_http_response_body)
    JSON.parse(api_http_response_body).dig('data', 'attributes', 'doi')
  end

  # @param api_http_response_body [String] the body content from the response generated by the DataCite REST API
  # @return [String] the doi state contained within the DataCite REST API response
  def parse_state_from_api_response_body(api_http_response_body)
    JSON.parse(api_http_response_body).dig('data', 'attributes', 'state')
  end

  # @param api_http_response_body [String] the body content from the response generated by the DataCite REST API
  # @return [String] the url contained within the DataCite REST API response
  def parse_url_from_api_response_body(api_http_response_body)
    JSON.parse(api_http_response_body).dig('data', 'attributes', 'url')
  end

  # see https://support.datacite.org/reference/dois-2#post_dois
  # 'Add a new doi.'
  # In other words, used to mint DOIs
  # @param request_body_json [String] string containing the payload (json) to be sent to the DataCite REST API
  # @return [Faraday::Response] response from the DataCite REST API
  def post_dois(request_body_json)
    conn = Faraday.new(@datacite_rest_api_url)
    conn.basic_auth(@basic_auth_user, @basic_auth_password)
    response = conn.post("/dois") do |req|
      req.headers['Content-Type'] = 'application/vnd.api+json'
      req.body = request_body_json
    end
    log("API response body: #{response.body}", DATACITE[:log_level]) if DATACITE[:log_api]
    response
  end

  # see https://support.datacite.org/reference/dois-2#put_dois-id
  # 'Update a doi.'
  # @param doi [String] DOI
  # @param request_body_json [String] string containing the payload (json) to be sent to the DataCite REST API
  # @return [Faraday::Response] response from the DataCite REST API
  def put_dois(doi, request_body_json)
    conn = Faraday.new(@datacite_rest_api_url)
    conn.basic_auth(@basic_auth_user, @basic_auth_password)
    response = conn.put("/dois/#{doi}") do |req|
      req.headers['Content-Type'] = 'application/vnd.api+json'
      req.body = request_body_json
    end
    log("API response body: #{response.body}", DATACITE[:log_level]) if DATACITE[:log_api]
    response
  end
end
