export const defaultItemRights = {
  descriptiveMetadata: [{
    typeOfContent: '',
    countryOfOrigin: {},
    filmDistributedToPublic: '',
    filmDistributedCommercially: '',
  }],
  copyrightStatus: [{
    copyrightStatement: {},
    note: '',
    copyrightRegistered: '',
    copyrightRenewed: '',
    copyrightDateOfRenewal: '',
    copyrightExpirationDate: '',
    culCopyrightAssessmentDate: '',
  }],
  copyrightOwnership: [{
    name: {},
    heirs: '',
    contactInformation: '',
  }],
  columbiaUniversityIsCopyrightHolder: [{
    dateOfTransfer: '',
    dateOfExpiration: '',
    transferDocumentation: '',
    otherTransferEvidence: '',
    transferDocumentationNote: '',
  }],
  licensedToColumbiaUniversity: [{
    dateOfLicense: '',
    terminationDateOfLicense: '',
    credits: '',
    acknowledgements: '',
    licenseDocumentationLocation: '',
  }],
  contractualLimitationsRestrictionsAndPermissions: [{
    optionA: false,
    optionB: false,
    optionC: false,
    optionD: false,
    optionE: false,
    optionAvA: false,
    optionAvB: false,
    optionAvC: false,
    optionAvD: false,
    optionAvE: false,
    optionAvF: false,
    optionAvG: false,
    reproductionAndDistributionProhibitedUntil: '',
    photographicOrFilmCredit: '',
    excerptLimitedTo: '',
    other: '',
    permissionsGrantedAsPartOfTheUseLicense: [],
  }],
  rightsForWorksOfArtSculptureAndPhotographs: [{
    publicityRightsPresent: '',
    trademarksProminentlyVisible: '',
    sensitiveInNature: '',
    privacyConcerns: '',
    childrenMateriallyIdentifiableInWork: '',
    varaRightsConcerns: '',
    note: '',
  }],
  underlyingRights: [{
    note: '',
    talentRights: '',
    columbiaMusicLicense: '',
    composition: '',
    recording: '',
    otherUnderlyingRights: [],
    other: '',
  }],
};

export const defaultAssetRights = {
  restrictionOnAccess: [{ // this might need to be displayed as multivalued in the form
    value: '',
    embargoReleaseDate: '',
    note: '',
    location: [{ term: {} }],
    affiliation: [{ value: '' }],
  }],
  copyrightStatusOverride: [{
    copyrightStatement: {},
    note: '',
    copyrightRegistered: '',
    copyrightRenewed: '',
    copyrightDateOfRenewal: '',
    copyrightExpirationDate: '',
    culCopyrightAssessmentDate: '',
  }],
};
