namespace :hyacinth do
  namespace :projects do

    # Durst namespace for Durst project tasks
    namespace :customerorders do
      
      task :add_collections => :environment do
        
        collection_names = [
          # Commented-out collections have already been added
          
          #"Albert Field Collection of Playing Cards",
          #"Albert Rhys Williams Papers",
          #"Albums of correspondence from Stanford White to his family",
          #"Albums Pertaining to Lermontov",
          #"Aleksei A. and Nadezhda V. Brusilov Papers",
          #"Alexander Gumby Collection of Negroiana",
          #"Alexander Jackson Davis Architectural Drawings and Papers",
          #"Alfred T. White Papers",
          #"Allen Ginsberg Papers",
          #"Anne S. Goodrich Collection",
          #"Annie Laurie Williams Records",
          #"Anton Seidl Collection of Musical Papers",
          #"Armenian Manuscripts Collection",
          #"Arthur Rackham Papers",
          #"Auchincloss Florence Nightingale Collection",
          #"Aymé Family Papers",
          #"Béla Bartók Manuscripts",
          #"Benckendorff Family Papers",
          #"Benjamin N. Cardozo Papers",
          #"Bennett Cerf Papers",
          #"Bonsall Family Papers",
          #"Book Arts Collection ",
          #"Boris Aleksandrovich Bakhmeteff Papers",
          #"Carnegie Corporation of New York Records",
          #"Carnegie Endowment for International Peace New York and Washington Offices records",
          #"Carnegie Endowment for International Peace European Center Records",
          #"Christine Ladd Franklin and Fabian Franklin Papers",
          #"Christodora House Records",
          #"Columbia College Records",
          #"Columbiana Manuscripts",
          #"Committee of Concerned Scientists Records",
          #"Community Service Society Records",
          #"Cornell Woolrich Papers",
          #"Daniel Longwell Papers",
          #"David Eugene Smith Collection of Historical Papers",
          #"Dawn Powell Papers",
          #"Delano & Aldrich Architectural Records and Papers",
          #"DeWitt Clinton Papers",
          #"Dietrich Bonhoeffer Primary Sources",
          #"Douglas Moore Papers",
          #"East Side House Records",
          #"Edward MacDowell Papers",
          #"Edward von Falz-Fein Memoirs",
          #"Edwin H. Armstrong Papers",
          #"Edwin Patrick Kilroe Papers",
          #"Elsie Worthington Clews Parsons Papers",
          #"Emilie Grace Briggs Papers",
          #"Empire State Building Archive",
          #"Ernest Nagel Papers",
          #"Ernst Jäckh Papers ",
          #"Esco Fund Committee, Inc. Records",
          #"Ethiopic Manuscripts Collection",
          #"Eugene Barry Papers",
          #"Florine Stettheimer Papers",
          #"Fort Ontario Emergency Refugee Center Records",
          #"Frances Perkins Papers",
          #"Frank Smithwick Hogan Papers",
          #"Frank Tannenbaum Papers",
          #"Frederic Dannay Papers",
          #"Frederick Ferris Thompson Collection",
          #"Frederick Paul Keppel Papers",
          #"Frederick Rolfe Papers",
          #"G.E.E. Lindquist Native American Collection",
          #"Georgii Mitrofanovich Kiselevskii Papers",
          #"Gillett Collection of American History and Theology",
          #"Graham Family Papers",
          #"Greene & Greene architectural drawings, papers and photographs",
          #"Gregory Corso Papers",
          #"Group Research, Inc. Records",
          #"Guastavino Fireproof Construction Company Architectural Records",
          #"H. Lawrence Freeman Papers",
          #"Hamilton Family Papers",
          #"Harlan Fiske Stone Papers",
          #"Harper & Brothers Records",
          #"Harper & Row, Publishers Records",
          #"Harrison E. Salisbury Papers",
          #"Hart Crane Papers",
          #"Helen Worden Erskine Papers",
          #"Henne Book Collection",
          #"Herbert Lionel Matthews Papers",
          #"Historical Map Collection",
          #"House of Books Ltd. Records",
          #"Institute of Pacific Relations Records",
          #"Ivan I. Morris Papers",
          #"James Lawrence Fly Papers",
          #"Jerome P. Webster collection of plastic surgery reprints",
          #"John Howard Griffin Papers",
          #"John Jay Papers",
          #"Joseph Urban Papers",
          #"Kahn & Jacobs architectural drawings and papers",
          #"Kent Family Papers",
          #"Kurt Goldstein Papers",
          #"Van Ess Collection",
          #"Lillian D. Wald Papers",
          #"Lincoln Steffens Papers",
          #"Lindsay Rogers Papers",
          #"Lionel Trilling Papers",
          #"Louis H. Sullivan photographs and drawings",
          #"Lucien Carr Papers",
          #"M. Moran Weston Papers",
          #"Marie Mattingly Meloney Papers",
          #"Marion E. Kenworthy Papers",
          #"Marion Meade Papers on Dorothy Parker",
          #"Mary Lasker Papers",
          #"McAlpin Collection of British History and Theology",
          #"Michael Idvorsky Pupin Papers",
          #"Mikhail Alexandrovich Taube Papers",
          #"Missionary Research Collection",
          #"Moncure Daniel Conway papers",
          #"Mother Mariia Papers",
          #"National Emergency Civil Liberties Committee (U.S.) Records",
          #"Ned Edward Hoopes Papers",
          #"New Leader Records",
          #"New York State Library School Records",
          #"Nicholas Murray Butler Papers",
          #"Nikola Tesla Papers",
          #"Nikolai Alekseevich Epanchin Memoirs",
          #"Nikolai Vasil'evich Zaretskii Papers",
          #"Ogden N. Rood Papers",
          #"Ol'ga Ivanovna Subbotina Papers",
          #"Pantheon Books Records",
          #"Paul Oskar Kristeller Papers",
          #"Peter H.L. and Edith Chang Papers",
          #"Philipse - Gouverneur Family Papers",
          #"PricewaterhouseCoopers Records",
          #"Prince Paul of Yugoslavia Papers",
          #"Pulitzer Prizes Collection",
          #"Randolph Silliman Bourne Papers ",
          #"Random House Records",
          #"Raymond M. Weaver Papers",
          #"Richard Hofstadter Papers",
          #"Robert Hiester Montgomery Manuscripts",
          #"Robert Joseph Flaherty Papers",
          #"Robert LaVigne Papers",
          #"Robert Lax Papers",
          #"Robert Sessions Woodworth Papers",
          #"Robert Underwood Johnson Papers",
          #"Robert Wilson Papers",
          #"Rockwell Kent Papers",
          #"Rose Nadler Franzblau Papers",
          #"Rudolf Wittkower Papers",
          #"Samuel and Bella Spewack Papers",
          #"Samuels Book Collection",
          #"Seligman Books",
          #"Sergei Viktorovich Potresov Papers",
          #"Shihui Xiong Papers",
          #"Siegfried Sassoon Papers",
          #"Sir Winston Churchill Papers",
          #"Soiuz Pazhei Records",
          #"Solton and Julia Engel Posters Collection",
          #"Spanish children's drawings of the Civil War collection",
          #"Spanish Refugee Relief Association Records",
          #"Stanford White Correspondence and Architectural Drawings",
          #"Stephen Crane Papers",
          #"Stephen Haweis Papers",
          #"Syriac Manuscripts Collection",
          #"Telford Taylor Papers ",
          #"Tennessee Williams Papers ",
          #"Thomas Carlyle Papers",
          #"Thomas Merton Papers",
          #"Thomas W. Lamb and John J. McNamara Architectural Records",
          #"Typographic Library Records",
          #"Union Settlement Association Records",
          #"Upjohn Collection of Architectural Drawings by Richard, Richard Michell, and Hobart Upjohn :Architectural Drawings, Papers, and Records",
          #"Fort Ontario Emergency Refugee Center Records",
          #"Van Cortlandt Family Papers",
          #"Varian Fry Papers",
          #"Varsity Show Records",
          #"W.W. Norton & Company Records",
          #"Wallace K. Harrison Architectural Drawings and Papers",
          #"Western Manuscripts",
          #"Whitney M. Young Papers",
          #"William Barclay Parsons Papers",
          #"William Brown Meloney Papers",
          #"William Peterfield Trent Papers",
          #"William Samuel Johnson Papers",
          #"X Manuscripts"
        ]
        
        collection_controlled_vocabulary = ControlledVocabulary.find_by(string_key: 'collection')
        
        collection_names.each do |name|
          AuthorizedTerm.create!(
            value: name,
            controlled_vocabulary: collection_controlled_vocabulary
          )
        end
        
      end
    
    end
  end
end
