development:
  url: https://ezid.cdlib.org
  user: apitest
  password: apitest
  prefix: '10.33555'
  shoulder:
    ark: ark:99999/fk4
    doi: doi:10.5072/FK2
  ezid_test_user: apitest
  ezid_test_password: apitest
  ezid_test_shoulder:
    ark: ark:99999/fk4
    doi: doi:10.5072/FK2
  ezid_publisher: Columbia University
  datacite:
    genre_to_resource_type_mapping:
      http://vocab.getty.edu/aat/300048715:
        attribute_general: Text
        content: Article
test:
  url: https://ezid.cdlib.org
  user: apitest
  password: apitest
  prefix: '10.33555'
  shoulder:
    ark: ark:99999/fk4
    doi: doi:10.5072/FK2
  ezid_test_user: apitest
  ezid_test_password: apitest
  ezid_test_shoulder:
    ark: ark:99999/fk4
    doi: doi:10.5072/FK2
  ezid_publisher: Columbia University
  datacite:
    genre_to_resource_type_mapping:
      http://vocab.getty.edu/aat/300048715:
        attribute_general: Text
        content: Article
