default: &default
  default_lang_value: en-US
  default_lang_subtags:
    Latn:
      type: script
      description: Latin
      added: '2005-10-16'
    en:
      type: language
      description: English
      suppress-script: Latn
      added: '2005-10-16'
    US:
      type: region
      description: United States
      added: '2005-10-16'

development:
  <<: *default

test:
  <<: *default
