development:
  collection:
    clio_id:
      display_label: CLIO ID
  location:
    code:
      display_label: Code
  name:
    name_type:
      display_label: Name Type
test:
  collection:
    clio_id:
      display_label: CLIO ID
  location:
    code:
      display_label: Code
  name:
    name_type:
      display_label: Name Type
